[package]
name = "spore-fates"
version = "1.0.0"
authors = ["Dan Van Eijck"]
edition = "2018"
description = "Common spore fates types"
license = "Apache-2.0"
repository = ""
homepage = ""
documentation = ""

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces

[dependencies]
cw2                  = { version = "2.0.0" }
cw20                 = { version = "2.0.0" } 
cosmwasm-schema      = { version = "2.2.2" }
cosmwasm-std         = { version = "2.2.2", features = [ "abort", "cosmwasm_1_2", "cosmwasm_1_3", "cosmwasm_1_4", "cosmwasm_2_0", "iterator", "stargate" ] }

cw721 = "0.20.0"

schemars = "0.8.22"
serde = { version = "1.0.219", default-features = false, features = ["derive"] }

base64 = "0.21"
